export const ERA_CONFIG = {
  1: {
    name: "Ancient Wonders",
    levels: [1, 20] as [number, number],
    description: "Pharaohs, philosophers, astronomers, builders",
    primaryTheme: "Foundational ethics, curiosity vs. conformity, intellectual courage",
    gradient: "linear-gradient(135deg, #1a2744 0%, #2d4a8c 50%, #1B6E6B 100%)",
    accentColor: "#E8A33D",
    textColor: "#ffffff",
    starField: true,
    ambientParticles: "stars" as const,
  },
  2: {
    name: "Age of Exploration",
    levels: [21, 40] as [number, number],
    description: "Sailors, cartographers, naturalists",
    primaryTheme: "Resilience, the unknown, cultural encounter",
    gradient: "linear-gradient(135deg, #1a3520 0%, #2d5a35 50%, #4F8B6E 100%)",
    accentColor: "#4F8B6E",
    textColor: "#ffffff",
    starField: false,
    ambientParticles: "waves" as const,
  },
  3: {
    name: "Renaissance & Reason",
    levels: [41, 60] as [number, number],
    description: "Galileo, da Vinci, early scientists and artists",
    primaryTheme: "Creative vision, truth vs. authority, courage to see differently",
    gradient: "linear-gradient(135deg, #2d1a44 0%, #4a2d6b 50%, #8B5FA3 100%)",
    accentColor: "#8B5FA3",
    textColor: "#ffffff",
    starField: false,
    ambientParticles: "dust" as const,
  },
  4: {
    name: "Industrial Innovation",
    levels: [61, 80] as [number, number],
    description: "Edison, Tesla, Ada Lovelace, early labor organizers",
    primaryTheme: "Iteration and failure, communication, ethics of invention",
    gradient: "linear-gradient(135deg, #3d1a0a 0%, #6b2d10 50%, #B85C2C 100%)",
    accentColor: "#B85C2C",
    textColor: "#ffffff",
    starField: false,
    ambientParticles: "steam" as const,
  },
  5: {
    name: "Space Age & Beyond",
    levels: [81, 100] as [number, number],
    description: "Astronauts, scientists, forward-looking innovators",
    primaryTheme: "Systems thinking, uncertainty, collective achievement",
    gradient: "linear-gradient(135deg, #0a1a3d 0%, #1a2d6b 50%, #5B6FA8 100%)",
    accentColor: "#5B6FA8",
    textColor: "#ffffff",
    starField: true,
    ambientParticles: "stars" as const,
  },
} as const

export type EraKey = keyof typeof ERA_CONFIG
